spring:
  thymeleaf:
    cache: false #开启缓存
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8

    #配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.105.27.58/ssmarkert?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: lovehxp521..

server:
  port: 8080

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
